import PDFDocument from 'pdfkit';
import { Response } from 'express';

export const generateChallanPDF = (challan: any, res: Response) => {
  const doc = new PDFDocument({ margin: 40, size: 'A4' });

  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename="${challan.challanNumber}.pdf"`);

  doc.pipe(res);

  // Header Banner
  doc
    .fillColor('#1E293B')
    .rect(0, 0, doc.page.width, 80)
    .fill('#0F172A');

  doc
    .fillColor('#FFFFFF')
    .fontSize(22)
    .font('Helvetica-Bold')
    .text('MINI ERP OPERATIONS PORTAL', 40, 25);

  doc
    .fontSize(12)
    .font('Helvetica')
    .text('Wholesale & Distribution Division', 40, 52);

  doc
    .fillColor('#38BDF8')
    .fontSize(16)
    .font('Helvetica-Bold')
    .text(`SALES CHALLAN`, 420, 30, { align: 'right' });

  doc
    .fillColor('#94A3B8')
    .fontSize(10)
    .font('Helvetica')
    .text(`#${challan.challanNumber}`, 420, 52, { align: 'right' });

  doc.moveDown(4);

  // Status & Metadata Bar
  const startY = 100;
  doc
    .fillColor('#1E293B')
    .fontSize(10)
    .font('Helvetica-Bold')
    .text('CHALLAN DETAILS', 40, startY);

  doc
    .font('Helvetica')
    .fontSize(9)
    .fillColor('#475569')
    .text(`Date: ${new Date(challan.createdAt).toLocaleDateString('en-IN', { dateStyle: 'medium' })}`, 40, startY + 18)
    .text(`Status: ${challan.status.toUpperCase()}`, 40, startY + 32)
    .text(`Generated By: ${challan.createdBy?.name || 'System User'}`, 40, startY + 46);

  // Customer Information Box
  doc
    .fillColor('#F8FAFC')
    .roundedRect(300, startY - 5, 250, 70, 6)
    .fill('#F1F5F9');

  doc
    .fillColor('#0F172A')
    .fontSize(10)
    .font('Helvetica-Bold')
    .text('CUSTOMER / BILL TO:', 310, startY);

  doc
    .font('Helvetica')
    .fontSize(9)
    .fillColor('#334155')
    .text(`${challan.customer?.businessName || challan.customer?.name}`, 310, startY + 16)
    .text(`Contact: ${challan.customer?.name} (${challan.customer?.mobile})`, 310, startY + 28)
    .text(`Email: ${challan.customer?.email}`, 310, startY + 40)
    .text(`GSTIN: ${challan.customer?.gstNumber || 'N/A'}`, 310, startY + 52);

  // Items Table Header
  const tableTop = startY + 90;
  doc
    .fillColor('#1E293B')
    .rect(40, tableTop, 515, 24)
    .fill('#334155');

  doc
    .fillColor('#FFFFFF')
    .fontSize(9)
    .font('Helvetica-Bold')
    .text('SKU', 50, tableTop + 7)
    .text('PRODUCT DESCRIPTION', 130, tableTop + 7)
    .text('UNIT PRICE', 320, tableTop + 7, { width: 70, align: 'right' })
    .text('QTY', 400, tableTop + 7, { width: 50, align: 'right' })
    .text('SUBTOTAL', 460, tableTop + 7, { width: 85, align: 'right' });

  let currentY = tableTop + 28;

  challan.items.forEach((item: any, index: number) => {
    const bg = index % 2 === 0 ? '#FFFFFF' : '#F8FAFC';
    doc.fillColor(bg).rect(40, currentY - 4, 515, 22).fill();

    doc
      .fillColor('#0F172A')
      .fontSize(9)
      .font('Helvetica')
      .text(item.productSku, 50, currentY)
      .text(item.productName, 130, currentY, { width: 180, lineBreak: false })
      .text(`₹${item.unitPrice.toFixed(2)}`, 320, currentY, { width: 70, align: 'right' })
      .text(`${item.quantity}`, 400, currentY, { width: 50, align: 'right' })
      .text(`₹${item.subtotal.toFixed(2)}`, 460, currentY, { width: 85, align: 'right' });

    currentY += 22;
  });

  // Table Bottom Divider
  doc.strokeColor('#CBD5E1').lineWidth(1).moveTo(40, currentY).lineTo(555, currentY).stroke();

  // Summary Totals
  const summaryY = currentY + 15;

  doc
    .fillColor('#F1F5F9')
    .roundedRect(330, summaryY, 225, 65, 4)
    .fill();

  doc
    .fillColor('#475569')
    .fontSize(9)
    .font('Helvetica')
    .text('Total Items Quantity:', 340, summaryY + 12)
    .text(`${challan.totalQuantity} units`, 470, summaryY + 12, { align: 'right' });

  doc
    .fillColor('#0F172A')
    .fontSize(12)
    .font('Helvetica-Bold')
    .text('Grand Total:', 340, summaryY + 36)
    .text(`₹${challan.totalAmount.toFixed(2)}`, 450, summaryY + 36, { width: 95, align: 'right' });

  // Footer / Terms
  const pageHeight = doc.page.height;
  doc
    .fillColor('#64748B')
    .fontSize(8)
    .font('Helvetica')
    .text('This is a computer-generated delivery challan & invoice.', 40, pageHeight - 50, { align: 'center' })
    .text('Thank you for your business! Mini ERP System.', 40, pageHeight - 38, { align: 'center' });

  doc.end();
};
