import React, { useState, useEffect } from 'react';
import { Search, Plus, FileText, Download, Eye, CheckCircle, XCircle } from 'lucide-react';
import { getChallansApi, updateChallanStatusApi, downloadChallanPDFApi } from '../services/api';
import { SalesChallan, Pagination as PaginationType } from '../types';
import { Badge } from '../components/Badge';
import { Pagination } from '../components/Pagination';
import { useAuth } from '../context/AuthContext';

interface ChallansProps {
  navigate: (path: string) => void;
}

export const Challans: React.FC<ChallansProps> = ({ navigate }) => {
  const { hasRole } = useAuth();
  const [challans, setChallans] = useState<SalesChallan[]>([]);
  const [pagination, setPagination] = useState<PaginationType>({ page: 1, limit: 10, total: 0, totalPages: 1 });
  const [search, setSearch] = useState('');
  const [statusFilter, setStatusFilter] = useState('');
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchChallans(1);
  }, [search, statusFilter]);

  const fetchChallans = async (page: number) => {
    try {
      setLoading(true);
      const res = await getChallansApi({
        search,
        status: statusFilter,
        page,
        limit: 10
      });
      setChallans(res.data);
      setPagination(res.pagination);
    } catch (err: any) {
      console.error('Failed to fetch sales challans', err);
    } finally {
      setLoading(false);
    }
  };

  const handleDownloadPDF = async (e: React.MouseEvent, ch: SalesChallan) => {
    e.stopPropagation();
    try {
      await downloadChallanPDFApi(ch.id, ch.challanNumber);
    } catch (err) {
      alert('Failed to generate PDF invoice.');
    }
  };

  const handleStatusChange = async (e: React.MouseEvent, id: string, newStatus: 'Confirmed' | 'Cancelled') => {
    e.stopPropagation();
    if (newStatus === 'Confirmed' && !window.confirm('Confirming this sales challan will automatically deduct stock from inventory. Proceed?')) {
      return;
    }
    try {
      await updateChallanStatusApi(id, newStatus);
      fetchChallans(pagination.page);
    } catch (err: any) {
      alert(err.response?.data?.message || 'Error updating status');
    }
  };

  return (
    <div>
      {/* Header Actions & Filters Bar */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.5rem', flexWrap: 'wrap', gap: '1rem' }}>
        <div style={{ display: 'flex', gap: '0.75rem', flex: 1, minWidth: '300px' }}>
          <div style={{ position: 'relative', flex: 1 }}>
            <Search size={18} color="#94A3B8" style={{ position: 'absolute', left: '12px', top: '50%', transform: 'translateY(-50%)' }} />
            <input
              type="text"
              className="form-input"
              style={{ paddingLeft: '2.4rem' }}
              placeholder="Search by Challan # or Customer Business Name..."
              value={search}
              onChange={(e) => setSearch(e.target.value)}
            />
          </div>

          <select className="form-select" style={{ width: '180px' }} value={statusFilter} onChange={(e) => setStatusFilter(e.target.value)}>
            <option value="">All Statuses</option>
            <option value="Draft">Draft Only</option>
            <option value="Confirmed">Confirmed Only</option>
            <option value="Cancelled">Cancelled Only</option>
          </select>
        </div>

        {hasRole('Admin', 'Sales') && (
          <button className="btn btn-primary" onClick={() => navigate('/challans/create')}>
            <Plus size={18} /> Generate Sales Challan
          </button>
        )}
      </div>

      {/* Challans Table */}
      <div className="card">
        <div className="card-body" style={{ padding: 0 }}>
          <div className="table-responsive">
            <table className="data-table">
              <thead>
                <tr>
                  <th>Challan #</th>
                  <th>Date</th>
                  <th>Customer</th>
                  <th>Items Count</th>
                  <th>Total Amount</th>
                  <th>Status</th>
                  <th>Generated By</th>
                  <th style={{ textAlign: 'right' }}>Actions</th>
                </tr>
              </thead>
              <tbody>
                {loading ? (
                  <tr>
                    <td colSpan={8} style={{ textAlign: 'center', padding: '2rem' }}>
                      Loading sales challans...
                    </td>
                  </tr>
                ) : challans.length === 0 ? (
                  <tr>
                    <td colSpan={8} style={{ textAlign: 'center', padding: '2rem', color: 'var(--text-muted)' }}>
                      No sales challans found.
                    </td>
                  </tr>
                ) : (
                  challans.map((ch) => (
                    <tr key={ch.id}>
                      <td><strong style={{ color: '#2563EB' }}>{ch.challanNumber}</strong></td>
                      <td style={{ fontSize: '0.825rem', color: 'var(--text-muted)' }}>
                        {new Date(ch.createdAt).toLocaleDateString('en-IN')}
                      </td>
                      <td>
                        <div style={{ fontWeight: 600 }}>{ch.customer?.businessName}</div>
                        <div style={{ fontSize: '0.775rem', color: 'var(--text-muted)' }}>{ch.customer?.name}</div>
                      </td>
                      <td>{ch.totalQuantity} units</td>
                      <td><strong>₹{ch.totalAmount.toLocaleString('en-IN')}</strong></td>
                      <td><Badge status={ch.status} /></td>
                      <td style={{ fontSize: '0.825rem' }}>{ch.createdBy?.name}</td>
                      <td style={{ textAlign: 'right' }}>
                        <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '0.35rem' }}>
                          <button
                            className="btn btn-secondary btn-sm"
                            title="View Challan Details"
                            onClick={() => navigate(`/challans/${ch.id}`)}
                          >
                            <Eye size={15} />
                          </button>

                          <button
                            className="btn btn-secondary btn-sm"
                            title="Download PDF Invoice"
                            onClick={(e) => handleDownloadPDF(e, ch)}
                          >
                            <Download size={15} color="#2563EB" /> PDF
                          </button>

                          {ch.status === 'Draft' && hasRole('Admin', 'Sales', 'Warehouse') && (
                            <button
                              className="btn btn-success btn-sm"
                              title="Confirm Challan & Deduct Stock"
                              onClick={(e) => handleStatusChange(e, ch.id, 'Confirmed')}
                            >
                              <CheckCircle size={14} /> Confirm
                            </button>
                          )}
                        </div>
                      </td>
                    </tr>
                  ))
                )}
              </tbody>
            </table>
          </div>
        </div>
      </div>

      <Pagination pagination={pagination} onPageChange={(p) => fetchChallans(p)} />
    </div>
  );
};
